theme: jekyll-theme-minimal
title: GeoMind - Documentos Legales
description: Políticas de privacidad, términos de servicio y más información legal para la aplicación GeoMind
show_downloads: false
logo: 
markdown: kramdown
